# Generated by Django 3.0.6 on 2020-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
